%YAML:1.0

image_height: 720
image_width: 960
use_imu: 0

depth_lower_thr: 0.1
depth_upper_thr: 10.0
max_y_diff: 2

# Calibration
distortion_type: 0  # 0 for undistorted inputs, 1 for radial-tangential: [k1, k2, p1, p2, k3], 2 for equidistant/fisheye:  [k1, k2, k3, k4, 0].
cam0:
  #intrinsics: [924.873180, 923.504522, 486.997346, 364.308527] # fx, fy, cx, cy
  intrinsics: [959.699489, 960.330103, 481.594807, 378.081732] # fx, fy, cx, cy
  distortion_coeffs: [0.026641, -0.035945, 0.006099, 0.000643, 0]
  T_type: 0           # 0 for Euroc format, the following T is Tbc. 1 for Kalibr format, the following T is Tcb
  T: 
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
cam1:
  intrinsics: [959.699489, 960.330103, 481.594807, 378.081732] # fx, fy, cx, cy
  distortion_coeffs: [0.026641, -0.035945, 0.006099, 0.000643, 0]
  T_type: 0           # 0 for Euroc format, the following T is Tbc. 1 for Kalibr format, the following T is Tcb
  T: 
  - [1.0, 0.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0, 0.0]
  - [0.0, 0.0, 1.0, 0.0]
  - [0.0, 0.0, 0.0, 1.0]
